# Generated by Django 5.0.3 on 2024-04-12 03:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaleMessengerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="uuid"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="created at"),
                ),
                (
                    "bale_id",
                    models.BigIntegerField(
                        db_index=True, unique=True, verbose_name="Bale ID"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                ("username", models.CharField(blank=True, verbose_name="username")),
                ("first_name", models.CharField(blank=True, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, verbose_name="last name")),
            ],
            options={
                "verbose_name": "bale user",
                "verbose_name_plural": "bale users",
            },
        ),
        migrations.AddConstraint(
            model_name="balemessengeruser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_number__isnull", False), _negated=True),
                fields=("phone_number",),
                name="unique_phone_number_when_bar_not_null",
            ),
        ),
    ]
