# Generated by Django 5.0.3 on 2024-04-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_balemessengeruser_employee_profile_user_is_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offrequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("TEMP", "موقت"),
                    ("EMPW", "در انتظار تایید کارفرما"),
                    ("ACPT", "تایید شده"),
                    ("RJCT", "رد شده"),
                ],
                default="TEMP",
                verbose_name="state",
            ),
        ),
    ]
